version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Install firebase-tools
          command: |
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install -y nodejs
            echo prefix=${HOME}/.local >> ~/.npmrc
            npm install -g firebase-tools
      - run: npm install
      - run:
          name: Build
          command: npm run generate
      - run:
          name: Deploy
          command: ~/.local/bin/firebase deploy --token $FIREBASE_TOKEN --project razokulover-com
